//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branches
    {
        public int ID { get; set; }
        public string Mfo { get; set; }
        public string Filial { get; set; }
        public string CBY { get; set; }
        public string Otdelenie { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Oblast { get; set; }
        public bool bDelete { get; set; }
        public Nullable<int> TypeODB { get; set; }
        public string AccountPayment { get; set; }
        public string UnpPayment { get; set; }
        public Nullable<System.TimeSpan> TimeCreationQuery { get; set; }
        public Nullable<bool> PreviousDay { get; set; }
        public string OutputDirectory { get; set; }
        public Nullable<int> ReportThen { get; set; }
        public string OblastTwo { get; set; }
        public string BikIban { get; set; }
        public Nullable<int> TypeOfSettelmentId { get; set; }
        public string Locality { get; set; }
        public string OrgSapId { get; set; }
        public Nullable<bool> OperationClose { get; set; }
    }
}
