// <auto-generated />
namespace EF_App.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class list_department2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(list_department2));
        
        string IMigrationMetadata.Id
        {
            get { return "202203171459598_list_department2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
